name: update
on:
  push:
    branches:
      - "main"

jobs:
  update:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@master
        with:
          node-version: 16.13.2

      - name: Install Dependencies
        run: npm install

      - name: Deploy Latest
        run: npm run deploy

      - name: Publish Page
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}